from setuptools import find_packages, setup


setup(name="epcore",
      version="0.1.22",
      description="A common set of key modules on the basis of which various software is built that works with "
                  "EyePoint signature analyzers",
      url="https://gitlab.ximc.ru/eyepoint/epcore",
      author="EPC MSU",
      author_email="info@physlab.ru",
      packages=find_packages(),
      python_requires=">=3.6, <=3.9.13",
      install_requires=[
          "dataclasses==0.8; python_version~='3.6.0'",
          "jsonschema==3.2.0",
          "numpy==1.18.1",
          "Pillow==8.0.1",
          "scipy==1.5.4"
      ],
      package_data={
          "epcore.analogmultiplexer": ["epmux/epmux-arm64/libepmux.so",
                                       "epmux/epmux-debian/libepmux.so",
                                       "epmux/epmux-win32/epmux.dll",
                                       "epmux/epmux-win64/epmux.dll"],
          "epcore.doc": ["p10_elements.schema.json",
                         "p10_elements_2.schema.json",
                         "ufiv.schema.json"],
          "epcore.ivmeasurer": ["ASA_device_settings.json",
                                "asa10/eplab_asa_options.json",
                                "asa10/libasa-debian/libasa.so",
                                "asa10/libasa-debian/libxmlrpc.so.3.51",
                                "asa10/libasa-debian/libxmlrpc_client.so.3.51",
                                "asa10/libasa-debian/libxmlrpc_util.so.4.51",
                                "asa10/libasa-debian/libxmlrpc_xmlparse.so.3.51",
                                "asa10/libasa-debian/libxmlrpc_xmltok.so.3.51",
                                "asa10/libasa-win32/asa.dll",
                                "asa10/libasa-win32/libxmlrpc.dll",
                                "asa10/libasa-win32/libxmlrpc_client.dll",
                                "asa10/libasa-win32/libxmlrpc_util.dll",
                                "asa10/libasa-win32/libxmlrpc_xmlparse.dll",
                                "asa10/libasa-win32/libxmlrpc_xmltok.dll",
                                "asa10/libasa-win64/asa.dll",
                                "asa10/libasa-win64/libxmlrpc.dll",
                                "asa10/libasa-win64/libxmlrpc_client.dll",
                                "asa10/libasa-win64/libxmlrpc_util.dll",
                                "asa10/libasa-win64/libxmlrpc_xmlparse.dll",
                                "asa10/libasa-win64/libxmlrpc_xmltok.dll",
                                "EyePoint_settings.json",
                                "EyePoint_virtual_device_settings.json",
                                "ivm02/ivm-arm64/libivm.so",
                                "ivm02/ivm-debian/libivm.so",
                                "ivm02/ivm-win32/ivm.dll",
                                "ivm02/ivm-win64/ivm.dll",
                                "ivm10/ivm-arm64/libivm.so",
                                "ivm10/ivm-debian/libivm.so",
                                "ivm10/ivm-win32/ivm.dll",
                                "ivm10/ivm-win64/ivm.dll"],
          "epcore.measurementmanager": ["ivcmp-arm64/libivcmp.so",
                                        "ivcmp-debian/libivcmp.so",
                                        "ivcmp-win32/ivcmp.dll",
                                        "ivcmp-win64/ivcmp.dll"],
          "epcore.product": ["doc/eplab_schema.json",
                             "eplab_default_options.json"]
      }
      )
